const macrotipos = [
    'Sin macrotipo',
    'Abuso de Autoridad',
    'Abuso sexual',
    'Afectación territorial',
    'Agresión física',
    'Amenaza',
    'Asesinato',
    'Atentado',
    'Atentado infraestructura indígena',
    'Confinamiento',
    'Consulta Previa',
    'Desalojo ilegal',
    'Desaparición',
    'Desplazamiento',
    'Estigmatización',
    'Extorsión',
    'Falso positivo',
    'Hostigamiento',
    'Hostigamientos',
    'Hurto',
    'Infracción D.I.H',
    'Intimidación',
    'Omisión del Estado',
    'Reclutamiento forzado',
    'Retención ilegal',
    'Secuestro',
    'Seguimiento',
    'Tortura',
    'Victima de MAP-MUSE',
    'Xenofobia'
]